# Generated by Django 5.0.4 on 2026-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='service',
        ),
        migrations.AddField(
            model_name='lead',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='leads', to='services.service', verbose_name='Услуги'),
        ),
    ]
